# Generated by Django 3.2.23 on 2023-11-18 00:14

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=file.models.get_upload_path),
        ),
    ]
