# Generated by Django 3.2.23 on 2023-11-26 07:43

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=file.models.get_upload_path),
        ),
    ]
